version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      rust-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      base-images:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: "/proofs/rekor-anchor/relayer"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      base-images:
        patterns: ["*"]
