[package]
name = "crowdrelay-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
url.workspace = true
base64.workspace = true
anyhow.workspace = true
async-trait.workspace = true
hmac.workspace = true
hex.workspace = true
getrandom.workspace = true
reqwest.workspace = true
ring.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
time.workspace = true
time-tz.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
crowdrelay-domain = { path = "../crowdrelay-domain" }
crowdrelay-application = { path = "../crowdrelay-application" }
crowdrelay-infra = { path = "../crowdrelay-infra" }
