// Deterministic owned-social platform pinning.
//
// A multi-platform social-post task may be generated by an LLM, but the
// channel choice is Brain policy once direct acquisition evidence exists.
// The durable task points back to the dispatch decision that froze that
// choice; outcomes on another platform are refused before any action is made.

impl AgentOutcomeWorker {
    /// The social channel Brain selected for the dispatch that produced this
    /// outcome. The durable task points back to its dispatch action, whose
    /// decision snapshot freezes the measured-channel choice.
    ///
    /// Missing agent-service schema or old tasks simply return None: those
    /// dispatches predate this contract and must remain ingestible.
    async fn selected_social_platform(&self, outcome: &ValidatedOutcome) -> Option<String> {
        let selected = sqlx::query_scalar::<_, Option<String>>(
            r#"
            SELECT decision.input_snapshot ->> 'selected_social_platform'
            FROM agent_service_tasks AS task
            JOIN autopilot_actions AS dispatch
              ON dispatch.workspace_id = task.workspace_id
             AND dispatch.id = CASE
                 WHEN task.metadata ->> 'action_id'
                      ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                 THEN (task.metadata ->> 'action_id')::uuid
                 ELSE NULL
             END
            JOIN autopilot_decisions AS decision
              ON decision.workspace_id = dispatch.workspace_id
             AND decision.id = dispatch.decision_id
            WHERE task.workspace_id = $1 AND task.id = $2
            "#,
        )
        .bind(outcome.workspace_id)
        .bind(outcome.task_id)
        .fetch_optional(&self.pool)
        .await;

        match selected {
            Ok(value) => value.flatten(),
            Err(error) => {
                tracing::debug!(
                    outcome_id = %outcome.id,
                    error = %error,
                    "could not resolve selected social platform; treating as legacy/unpinned task"
                );
                None
            }
        }
    }


}
