-- Replace the optional EVM anchor with a neutral Rekor transparency receipt.
-- Migration 0020 remains intact for already-applied databases. Its chain-shaped
-- columns are retained only for historical compatibility and are no longer used.

INSERT INTO ecosystem_feature_flags (
    workspace_id, key, enabled, reason, version, updated_at, updated_by_request_id
)
SELECT workspace_id,
       'external_proof_anchoring_enabled',
       enabled,
       'renamed from blockchain_anchoring_enabled',
       version,
       updated_at,
       updated_by_request_id
FROM ecosystem_feature_flags
WHERE key = 'blockchain_anchoring_enabled'
ON CONFLICT (workspace_id, key) DO UPDATE
SET enabled = EXCLUDED.enabled,
    reason = EXCLUDED.reason,
    version = GREATEST(ecosystem_feature_flags.version, EXCLUDED.version),
    updated_at = GREATEST(ecosystem_feature_flags.updated_at, EXCLUDED.updated_at),
    updated_by_request_id = EXCLUDED.updated_by_request_id;

INSERT INTO ecosystem_feature_flags (workspace_id, key, enabled, reason)
SELECT id, 'external_proof_anchoring_enabled', false, 'Rekor anchor default'
FROM workspaces
ON CONFLICT (workspace_id, key) DO NOTHING;

DELETE FROM ecosystem_feature_flags
WHERE key = 'blockchain_anchoring_enabled';

ALTER TABLE external_proof_batches
    ADD COLUMN anchor_kind text,
    ADD COLUMN anchor_url text,
    ADD COLUMN anchor_entry_id text,
    ADD COLUMN anchor_sequence bigint,
    ADD COLUMN anchor_integrated_at timestamptz,
    ADD COLUMN anchor_log_id text,
    ADD COLUMN anchor_receipt jsonb,
    ADD COLUMN signer_fingerprint text,
    ADD COLUMN signed_payload_sha256 bytea;

-- Preserve any historical EVM confirmations without enabling new EVM writes.
UPDATE external_proof_batches
SET anchor_kind = 'legacy.evm',
    anchor_url = chain_namespace || ':' || chain_id::text,
    anchor_entry_id = transaction_hash,
    anchor_sequence = transaction_batch_index,
    anchor_integrated_at = confirmed_at,
    anchor_log_id = block_hash,
    anchor_receipt = jsonb_build_object(
        'legacy', true,
        'chain_namespace', chain_namespace,
        'chain_id', chain_id,
        'contract_address', contract_address,
        'transaction_hash', transaction_hash,
        'block_number', block_number,
        'transaction_batch_index', transaction_batch_index,
        'block_hash', block_hash
    ),
    signer_fingerprint = 'legacy:unknown',
    signed_payload_sha256 = root_sha256
WHERE status = 'confirmed' AND anchor_kind IS NULL;

-- Drop only the old chain-dependent checks; names are generated by PostgreSQL.
DO $$
DECLARE
    constraint_name text;
BEGIN
    FOR constraint_name IN
        SELECT conname
        FROM pg_constraint
        WHERE conrelid = 'external_proof_batches'::regclass
          AND contype = 'c'
          AND pg_get_constraintdef(oid) LIKE '%chain_namespace%'
    LOOP
        EXECUTE format(
            'ALTER TABLE external_proof_batches DROP CONSTRAINT %I',
            constraint_name
        );
    END LOOP;
END
$$;

DROP INDEX IF EXISTS external_proof_batches_chain_tx_idx;

ALTER TABLE external_proof_batches
    ADD CONSTRAINT external_proof_batches_anchor_kind_check CHECK (
        anchor_kind IS NULL OR anchor_kind IN ('sigstore.rekor.v1', 'legacy.evm')
    ),
    ADD CONSTRAINT external_proof_batches_anchor_url_check CHECK (
        anchor_url IS NULL OR (char_length(anchor_url) BETWEEN 3 AND 512 AND btrim(anchor_url) = anchor_url)
    ),
    ADD CONSTRAINT external_proof_batches_anchor_entry_check CHECK (
        anchor_entry_id IS NULL OR char_length(anchor_entry_id) BETWEEN 3 AND 256
    ),
    ADD CONSTRAINT external_proof_batches_anchor_sequence_check CHECK (
        anchor_sequence IS NULL OR anchor_sequence >= 0
    ),
    ADD CONSTRAINT external_proof_batches_anchor_log_id_check CHECK (
        anchor_log_id IS NULL OR char_length(anchor_log_id) BETWEEN 3 AND 256
    ),
    ADD CONSTRAINT external_proof_batches_signer_fingerprint_check CHECK (
        signer_fingerprint IS NULL OR char_length(signer_fingerprint) BETWEEN 8 AND 160
    ),
    ADD CONSTRAINT external_proof_batches_signed_payload_check CHECK (
        signed_payload_sha256 IS NULL OR octet_length(signed_payload_sha256) = 32
    ),
    ADD CONSTRAINT external_proof_batches_anchor_state_check CHECK (
        (
            status = 'confirmed'
            AND anchor_kind IS NOT NULL
            AND anchor_url IS NOT NULL
            AND anchor_entry_id IS NOT NULL
            AND anchor_sequence IS NOT NULL
            AND anchor_integrated_at IS NOT NULL
            AND anchor_log_id IS NOT NULL
            AND anchor_receipt IS NOT NULL
            AND signer_fingerprint IS NOT NULL
            AND signed_payload_sha256 IS NOT NULL
            AND confirmed_at IS NOT NULL
        )
        OR (
            status <> 'confirmed'
            AND anchor_kind IS NULL
            AND anchor_url IS NULL
            AND anchor_entry_id IS NULL
            AND anchor_sequence IS NULL
            AND anchor_integrated_at IS NULL
            AND anchor_log_id IS NULL
            AND anchor_receipt IS NULL
            AND signer_fingerprint IS NULL
            AND signed_payload_sha256 IS NULL
            AND confirmed_at IS NULL
        )
    ),
    ADD CONSTRAINT external_proof_batches_rekor_shape_check CHECK (
        anchor_kind <> 'sigstore.rekor.v1'
        OR (
            anchor_url ~ '^https://[^[:space:]]+$'
            AND anchor_entry_id ~ '^[0-9a-f]{64,128}$'
            AND anchor_log_id ~ '^[0-9a-f]{64}$'
            AND signer_fingerprint ~ '^sha256:[0-9a-f]{64}$'
            AND jsonb_typeof(anchor_receipt) = 'object'
        )
    );

CREATE UNIQUE INDEX external_proof_batches_anchor_entry_idx
    ON external_proof_batches (
        workspace_id, anchor_kind, anchor_url, anchor_entry_id, anchor_sequence
    )
    WHERE anchor_entry_id IS NOT NULL;
