-- Add 'community' as a valid target_kind and a subreddit column for
-- community-kind outreach targets. Reddit communities are public spaces,
-- not personal contacts — the growth loop auto-promotes them to 'promoted'
-- on insert so the brain can dispatch the community-engager without operator
-- review. Personal-contact kinds (press, radio, creator, etc.) keep the
-- proposed → promoted operator-approval flow.
--
-- The subreddit column stores the clean subreddit name (without r/ prefix)
-- so the community-engager prompt and the community.engage.request action
-- payload can carry it without parsing display_name.
--
-- Idempotent: guarded by DO blocks so re-running the migration is safe.

DO $$
BEGIN
    -- Drop the existing CHECK on target_kind and replace with one that
    -- includes 'community'. The constraint name is auto-generated by
    -- Postgres from the column name + _check suffix.
    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'agent_outreach_targets'::regclass
          AND contype = 'c'
          AND pg_get_constraintdef(oid) LIKE '%target_kind%'
    ) THEN
        ALTER TABLE agent_outreach_targets
            DROP CONSTRAINT agent_outreach_targets_target_kind_check;
    END IF;
END $$;

ALTER TABLE agent_outreach_targets
    DROP CONSTRAINT IF EXISTS agent_outreach_targets_target_kind_check;

ALTER TABLE agent_outreach_targets
    ADD CONSTRAINT agent_outreach_targets_target_kind_check
    CHECK (target_kind IN (
        'press', 'radio', 'playlist', 'media_patronage',
        'endorsement', 'creator', 'community'
    ));

ALTER TABLE agent_outreach_targets
    ADD COLUMN IF NOT EXISTS subreddit TEXT
    CHECK (subreddit IS NULL OR (btrim(subreddit) <> '' AND char_length(subreddit) <= 100));

-- Index for efficiently finding promoted community targets with a subreddit
-- (the snapshot loader uses this to build the community-engager prompt).
CREATE INDEX IF NOT EXISTS agent_outreach_targets_community_subreddit_idx
    ON agent_outreach_targets (workspace_id, target_kind, status)
    WHERE target_kind = 'community' AND status = 'promoted' AND subreddit IS NOT NULL;
