[package]
name = "crowdrelay-application"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
serde.workspace = true
thiserror.workspace = true
time.workspace = true
crowdrelay-domain = { path = "../crowdrelay-domain" }

[dev-dependencies]
tokio.workspace = true
